# Copyright 2020 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

steps:
  - label: "build"
    commands:
      - "git submodule update --init --jobs 8 --depth 1"
      - "docker run --user=$(id -u):$(id -g) --volume=\\$PWD:\\$IREE_DOCKER_WORKDIR --workdir=\\$IREE_DOCKER_WORKDIR --rm gcr.io/iree-oss/android@sha256:ffb02ab2a7c5ee7bb1bcae9fb08d0de70cdb3c42466a4951e48d9142cc9b8ca2 build_tools/cmake/build_android.sh arm64-v8a"
      - "tar --exclude='*.o' --exclude='*.a' -czvf build-artifacts.tgz build-android"
    agents:
      - "queue=build"
    env:
      IREE_DOCKER_WORKDIR: "/usr/src/github/iree"
    artifact_paths: "build-artifacts.tgz"

  - wait

  - label: "test on Pixel 6 (google-tensor, mali-g78)"
    commands:
      - "git clean -fdx"
      - "buildkite-agent artifact download --step build build-artifacts.tgz ./"
      - "tar xzf build-artifacts.tgz"
      - "find build-android/ -name '*.cmake' -exec sed -i \"s!\\$IREE_DOCKER_WORKDIR/!\\$PWD/!g\" {} \\;"
      - "cd build-android/"
      - "ctest --timeout 900 --output-on-failure"
    agents:
      - "android-soc=google-tensor"
      - "queue=test-android"
    env:
      IREE_DOCKER_WORKDIR: "/usr/src/github/iree"
    timeout_in_minutes: "15"

  - label: "test on Pixel 4 (snapdragon-855, adreno-640)"
    commands:
      - "git clean -fdx"
      - "buildkite-agent artifact download --step build build-artifacts.tgz ./"
      - "tar xzf build-artifacts.tgz"
      - "find build-android/ -name '*.cmake' -exec sed -i \"s!\\$IREE_DOCKER_WORKDIR/!\\$PWD/!g\" {} \\;"
      - "cd build-android/"
      # vulkan tests using khr_shader_float16_int8 are failing on pixel4.
      # Disabling it until we identify the root cause.
      - "ctest --timeout 900 --output-on-failure --label-exclude \"^vulkan_uses_vk_khr_shader_float16_int8\\$\""
    agents:
      - "android-soc=snapdragon-855"
      - "queue=test-android"
    env:
      IREE_DOCKER_WORKDIR: "/usr/src/github/iree"
    timeout_in_minutes: "15"

notify:
  - email: "bdi-build-cop+buildkite@grotations.appspotmail.com"
    if: build.state == "failed"
