# Copyright 2020 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

steps:
  - label: "build"
    commands:
      - "docker run --user=$(id -u):$(id -g) --volume=\\$PWD:\\$IREE_DOCKER_WORKDIR --workdir=\\$IREE_DOCKER_WORKDIR --rm gcr.io/iree-oss/cmake-android@sha256:0981a75325547d1bd5771290287cb8ef09181c4c127972d17132405394478ffb build_tools/kokoro/gcp_ubuntu/cmake/android/build.sh arm64-v8a"
      - "tar --exclude='*.o' --exclude='*.a' -czvf build-artifacts.tgz build-android"
    agents:
      - "queue=build"
    env:
      IREE_DOCKER_WORKDIR: "/usr/src/github/iree"
    artifact_paths: "build-artifacts.tgz"

  - wait

  - label: "test on Galaxy S20 (exynos-990, mali-g77)"
    commands:
      - "buildkite-agent artifact download --step build build-artifacts.tgz ./"
      - "tar xzf build-artifacts.tgz"
      - "find build-android/ -name '*.cmake' -exec sed -i \"s!\\$IREE_DOCKER_WORKDIR/!\\$PWD/!g\" {} \\;"
      - "cd build-android/"
      - "ctest --timeout 900 --output-on-failure"
    agents:
      - "android-soc=exynos-990"
      - "queue=test-android"
    env:
      IREE_DOCKER_WORKDIR: "/usr/src/github/iree"
    timeout_in_minutes: "15"

  - label: "test on Galaxy S10 (exynos-9820, mali-g76)"
    commands:
      - "buildkite-agent artifact download --step build build-artifacts.tgz ./"
      - "tar xzf build-artifacts.tgz"
      - "find build-android/ -name '*.cmake' -exec sed -i \"s!\\$IREE_DOCKER_WORKDIR/!\\$PWD/!g\" {} \\;"
      - "cd build-android/"
      - "ctest --timeout 900 --output-on-failure"
    agents:
      - "android-soc=exynos-9820"
      - "queue=test-android"
    env:
      IREE_DOCKER_WORKDIR: "/usr/src/github/iree"
    timeout_in_minutes: "15"

  - label: "test on Pixel 4 (snapdragon-855, adreno-640)"
    commands:
      - "buildkite-agent artifact download --step build build-artifacts.tgz ./"
      - "tar xzf build-artifacts.tgz"
      - "find build-android/ -name '*.cmake' -exec sed -i \"s!\\$IREE_DOCKER_WORKDIR/!\\$PWD/!g\" {} \\;"
      - "cd build-android/"
      # vulkan tests using khr_shader_float16_int8 are failing on pixel4.
      # Disabling it until we identify the root cause.
      - "ctest --timeout 900 --output-on-failure --label-exclude \"^vulkan_uses_vk_khr_shader_float16_int8\\$\""
    agents:
      - "android-soc=snapdragon-855"
      - "queue=test-android"
    env:
      IREE_DOCKER_WORKDIR: "/usr/src/github/iree"
    timeout_in_minutes: "15"

notify:
  - email: "bdi-build-cop+buildkite@grotations.appspotmail.com"
    if: build.state == "failed"
