# Builds the TFLite Java Bindings Android Library using the gradle-android
# Docker image.
name: Build TFLite Android Library

on:
  workflow_dispatch:

jobs:
  build_android_with_docker:
    runs-on: ubuntu-latest
    env:
      ANDROID_CONTAINER: "gcr.io/iree-oss/gradle-android@sha256:8ea3563fa233ff22bd6f190ec3d4ad28b542a80efd9300bd60dfbe6b809e490c"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Execute Android Build
        run: |
          docker run --rm \
          -w=/work \
          -v $PWD:/work \
          "${ANDROID_CONTAINER}" \
          bash -c build_tools/gradle/build_tflite_android_library.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./bindings/tflite/java/build/outputs/aar/*.aar
          retention-days: 1
