name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installing bazel
        run: |
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt install curl
          curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
          sudo apt update && sudo apt install bazel
      - name: Installing dependencies
        run: |
          sudo apt install clang python3 python3-pip
          sudo pip install numpy
      - name: Checking out latest version and all submodules
        run: |
          git config --global remote.origin.fetch '+refs/pull/*:refs/remotes/origin/pull/*'
          git clone https://github.com/$GITHUB_REPOSITORY $GITHUB_WORKSPACE --no-checkout --no-tags
          git checkout $GITHUB_SHA
          git submodule update --init --depth 1000 --jobs 8
      - name: Building with bazel
        env:
          CXX: clang++
          CC: clang
          PYTHON_BIN: /usr/bin/python3
        run: |
          bazel build iree/...
